### PR TITLE
Fix: Change wrong 'ddefault' with 'default' reference

### PR DESCRIPTION
**Pull request by pedroamador**
@Shashikant86 there is a typo in a config option key name

### CODE REVIEW

**Comment by Shashikant86** [comment]
Oops! Sorry about the typo. I will merge this PR now. Thanks for spotting and fixing! @pedroamador

**Comment by Shashikant86** [comment]
I will create a new release tonight!

**Comment by pedroamador** [comment]
Cool, thanks @Shashikant86

We are using BDDFire in the Day 6 of our Docker Learning course :)
https://github.com/kairops/docker-learning

**Comment by Shashikant86** [comment]
Glad to hear that @pedroamador. I have pushed new version `3.0.2`

**Comment by pedroamador** [comment]
Thanks @Shashikant86 

I will test this release of the library today

**Pull request merged**
